name: swipe_overlays
description: Swipe Overlays
publish_to: none
version: 0.1.1

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=3.0.5"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^3.0.1

flutter:
  assets:
    - images/

  uses-material-design: true
