name: swipe_overlays
description: Swipe Overlays
publish_to: none
version: 0.1.1

environment:
  sdk: ^3.6.0
  flutter: ^3.27.0

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^7.0.0

flutter:
  assets:
    - images/

  uses-material-design: true
