name: swipe_overlays
description: Swipe Overlays
version: 1.0.0+1

environment:
  sdk: ">=2.14.0 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^0.14.0+3

dev_dependencies:
  akaiser_flutter_lints:
    git: https://github.com/akaiser/akaiser_flutter_lints.git
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - images/

  uses-material-design: true
